### ISSUE TITLE
If i run a command, it gets deleted and the command doesnt run.

### ISSUE THREAD

**Issue by Deccr** [Kappador/satana#2]
When i run **ANY** command, the message i ran the command in gets deleted, and i get no reply from the bot, checked my console, and got nothing, ive removed a few commands that i dont need because my server is based on a family friendly pg streamer, is that an issue?

**Comment by cnriscute** [comment]
Hi, can you add me on Discord?

Conner#1386

**Comment by Deccr** [comment]
aight have done im statham.json

**Comment by AkgunFatih** [comment]
i have the same issue

**Comment by Kappador** [comment]
Message me on discord Kappador#1939
